### ISSUE TITLE
Ground issues

### ISSUE THREAD

**Issue by SilverBulletTen** [abdulkadiraktas/RedEMRp_txAdminRecipe#1]
I loaded this into my server and it went super smooth. Thanks for the txadmin installer. However the ground is glitch and things fall thrown the ground and doesn't load the roads in some parts of the map. I was in blackwater and by the sheriffs office and towards the government building the whole floor is missing. Any idea how to fix this?

![20220317131043_1](https://user-images.githubusercontent.com/98196614/158856818-6db5432e-0cd5-4462-bf70-a85e57e174d9.jpg)

**Comment by abdulkadiraktas** [comment]
this is redm issue. You need run IPL script for IPL's.
